apiVersion: v1
kind: Service
metadata:
  labels:
    app: CwIndustriessrv
    service: CwIndustriessrv
  name: CwIndustriessrv
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: CwIndustries